.LOGTABLE EMP_STG_LT1313;
LOGON 10.58.0.66/td_user24;
.BEGIN IMPORT MLOAD
 TABLES      EMPLOYEE_STG1_1313,EMPLOYEE_STG2_1313
 WORKTABLES  EMPLOYEE_WT1_1313,EMPLOYEE_WT2_1313
 ERRORTABLES EMPLOYEE_ET1313 EMPLOYEE_UV1313,
 EMPLOYEE1_ET21313 EMPLOYEE1_UV21313 ;

.LAYOUT EMPLOYEE_STG13;
.FIELD in_EmployeeNo * VARCHAR(10);
.FIELD in_FirstName * VARCHAR(30);
.FIELD in_LastName * VARCHAR(30);
.FIELD in_BirthDate * VARCHAR(10);
.FIELD in_JoinedDate * VARCHAR(10);
.FIELD in_DepartmentNo * VARCHAR(02);

 .DML LABEL EMPLOYEE_STG1_1313 ;

 INSERT INTO EMPLOYEE_STG1_1313  VALUES
 (:in_EmployeeNo,
  :in_FirstName,
  :in_Lastname,
  :in_BirthDate, 
  :in_JoinedDate,
  :in_DepartmentNo);


 .DML LABEL EMPLOYEE_STG2_1313 ;

 INSERT INTO EMPLOYEE_STG2_1313 VALUES
 (:in_EmployeeNo,
  :in_FirstName,
  :in_Lastname,
  :in_BirthDate, 
  :in_JoinedDate,
  :in_DepartmentNo);

.IMPORT INFILE emp.txt

  LAYOUT EMPLOYEE_STG13

  FORMAT VARTEXT ','

  APPLY EMPLOYEE_STG1_1313

  APPLY EMPLOYEE_STG2_1313;

 .END MLOAD;

 .LOGOFF;